---
language: python
services: docker

install:
  - pip install -U pip
  - pip --version
  - pip install ansible ansible-lint yamllint flake8 molecule docker
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

script:
  - molecule lint
  - molecule test
  - flake8 $(find . -name '*.py')

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
