---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: instance
    image: centos:7

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
